language: python
sudo: required
dist: xenial
python:
  - '3.7'
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - coverage run --source steamtags setup.py test
after_success:
  - codecov